version: "3.9"

services:
  back:
    build: .
    container_name: PipeArchitectBack
    ports:
      - "7820:5000"
    command: ["flask", "run", "--host=0.0.0.0", "-p 7820"]
    volumes:
      - ./app:/tmp/app
      - ./.data:/tmp/.data

  front:
    container_name: PipeArchitectFront
    image: app-dev
    build:
      context: .
      target: development
    volumes:
      - app/frontend/src:/tmp/app/frontend/src
    ports:
      - 7821:3000